
CREATE TABLE ATUACAO(
  ID INT IDENTITY NOT NULL PRIMARY KEY,
  NOME VARCHAR(30) NOT NULL,
  ATIVO VARCHAR(3) DEFAULT 'SIM' NOT NULL
);

CREATE TABLE PESSOA(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_FK_PESSOA INT,
  NOME VARCHAR(40) NOT NULL, 
  RG_IE VARCHAR(20),
  CPF_CNPJ VARCHAR(14) NOT NULL,
  LOGRADOURO VARCHAR(40),
  NUMERO VARCHAR(10),
  CEP VARCHAR(9),
  BAIRRO VARCHAR(30),
  CIDADE VARCHAR(30),
  UF VARCHAR(2),
  ATIVO VARCHAR(3) DEFAULT 'SIM' NOT NULL,

  CONSTRAINT FK_PESSOA  FOREIGN KEY (ID_FK_PESSOA) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE PESSOA_ATUA(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_PESSOA INT NOT NULL,
  ID_ATUACAO INT NOT NULL,
  ATIVO VARCHAR(3),

  CONSTRAINT FK_PESSOA_ATUA  FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT FK_ATUACAO_PESSOA  FOREIGN KEY (ID_ATUACAO) REFERENCES ATUACAO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE UNIDADE_MEDIDA(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  NOME VARCHAR(20) NOT NULL,
  SIGLA VARCHAR(3) NOT NULL
);

CREATE TABLE INSUMO_PRODUTO(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  NOME VARCHAR(30) NOT NULL,
  INSUMO_PRODUTO VARCHAR(1) NOT NULL,
  FATOR_CORRECAO NUMERIC(4,2) NOT NULL,
  FATOR_PERDA NUMERIC(4,2) NOT NULL,
  ESTOOUE NUMERIC(6,2) DEFAULT 0 NOT NULL,
  ATIVO VARCHAR(3) DEFAULT 'SIM' NOT NULL
);

CREATE TABLE FICHA_TECNICA(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_UNI_MEDIDA INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
	ID_INSUMO INT NOT NULL,
  QTDE_INSUMO NUMERIC(6,2) NOT NULL,

  CONSTRAINT FK_FIC_TECNICA_UNI_MEDIDA  FOREIGN KEY (ID_UNI_MEDIDA) REFERENCES UNIDADE_MEDIDA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT FK_FIC_TECNICA_INSUMO  FOREIGN KEY (ID_PRODUTO) REFERENCES INSUMO_PRODUTO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT FK_FIC_TECNICA_PRODUTO  FOREIGN KEY (ID_INSUMO) REFERENCES INSUMO_PRODUTO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT UQ_UNI_MEDIDA_INSUMO UNIQUE (ID_UNI_MEDIDA, ID_PRODUTO, ID_INSUMO)
);

CREATE TABLE MEIO_PAGAMENTO(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  NOME VARCHAR(30) NOT NULL,
  ATIVO VARCHAR(3) DEFAULT 'SIM' NOT NULL
);

CREATE TABLE PARCELA(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  QTDE_PARCELA SMALLINT NOT NULL,
  DIA_INTERVALO SMALLINT NOT NULL,
  ATIVO VARCHAR(3) DEFAULT 'SIM' NOT NULL
);

CREATE TABLE MEIO_PAGTO_PARCELA(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_MEIO_PAGAMENTO INT NOT NULL,
  ID_PARCELA INT NOT NULL,

  CONSTRAINT UQ_MEIO_PARCELA_PAGTO UNIQUE (ID_MEIO_PAGAMENTO, ID_PARCELA),

  CONSTRAINT FK_MEIO_PAGTO_PARCELA FOREIGN KEY (ID_MEIO_PAGAMENTO) REFERENCES MEIO_PAGAMENTO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT FK_PARCELA_MEIO_PAGTO FOREIGN KEY (ID_PARCELA) REFERENCES PARCELA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE PEDIDO(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_FILIAL INT NOT NULL,
  ID_REMETENTE INT NOT NULL,
  ID_DESTINATARIO INT NOT NULL,
  ID_USUARIO INT NOT NULL,
  ID_MEIO_PAGTO_PARCELA INT,
  ENTRADA_SAIDA VARCHAR(1) NOT NULL,
  TOTAL_ITEM NUMERIC(6,2) NOT NULL,
  TOTAL_DESCONTO NUMERIC(6,2) NOT NULL,
  TOTAL_ACRESCIMO NUMERIC(6,2) NOT NULL,
  VALOR_FRETE NUMERIC(6,2) DEFAULT 0,
  TOTAL_PEDIDO NUMERIC(7,2) NOT NULL,
  STATUS VARCHAR(2),
  DATA_PEDIDO DATE NOT NULL,

 CONSTRAINT FK_PEDIDO_FILIAL  FOREIGN KEY (ID_FILIAL) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

 CONSTRAINT FK_PEDIDO_REQUISITANTE  FOREIGN KEY (ID_REMETENTE) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

 CONSTRAINT FK_PEDIDO_DESTINATARIO  FOREIGN KEY (ID_DESTINATARIO) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

 CONSTRAINT FK_PEDIDO_USUARIO  FOREIGN KEY (ID_USUARIO) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

 CONSTRAINT FK_PEDIDO_PAGTO FOREIGN KEY (ID_MEIO_PAGTO_PARCELA) REFERENCES MEIO_PAGTO_PARCELA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE PEDIDO_ITEM(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_PEDIDO INT NOT NULL,
  ID_INSUMO_PRODUTO INT NOT NULL,
  QTDE_PRODUTO NUMERIC(6,2) NOT NULL,
  PRECO_ITEM NUMERIC(6,2) NOT NULL,
  TOTAL_ITEM NUMERIC(6,2) NOT NULL,
  PERCENTUAL_DESCONTO NUMERIC(5,2) DEFAULT 0,
  VALOR_DESCONTO NUMERIC(6,2),
  PERCENTUAL_ACRESCIMO NUMERIC(5,2),
  VALOR_ACRESCIMO NUMERIC(6,2),
  VALOR_FRETE NUMERIC(6,2) DEFAULT 0,
  TOTAL_GERAL_ITEM NUMERIC(7,2) NOT NULL,

   CONSTRAINT FK_PEDIDO_ITEM FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

   CONSTRAINT FK_PRODUTO_ITEM FOREIGN KEY (ID_INSUMO_PRODUTO) REFERENCES INSUMO_PRODUTO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE MOVIMENTACAO(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_PEDIDO INT,
  ID_DEVOLUCAO INT,
  ID_MEIO_PAGTO_PARCELA INT,
  TIPO_MOVIMENTACAO VARCHAR(2) NOT NULL,
  NUMERO_DOCUMENTO INT NOT NULL,
  TOTAL_ITEM NUMERIC(6,2) NOT NULL,
  TOTAL_DESCONTO NUMERIC(6,2) NOT NULL,
  TOTAL_ACRESCIMO NUMERIC(6,2) NOT NULL,
  VALOR_FRETE NUMERIC(6,2) DEFAULT 0,
  TOTAL_MOVIMENTACAO NUMERIC(7,2) NOT NULL,
  DATA_ENTRADA_SAIDA DATE NOT NULL,
  HORA_ENTRADA_SAIDA TIME NOT NULL, 
  STATUS VARCHAR(2),

 CONSTRAINT FK_PEDIDO_MOVIMENTACAO  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

 CONSTRAINT FK_DEVOLUCAO  FOREIGN KEY (ID_DEVOLUCAO) REFERENCES MOVIMENTACAO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

 CONSTRAINT FK_PAGTO FOREIGN KEY (ID_DEVOLUCAO) REFERENCES MEIO_PAGTO_PARCELA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE MOVIMENTACAO_ITEM(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_MOVIMENTACAO INT NOT NULL,
  ID_INSUMO_PRODUTO INT NOT NULL,
  QTDE_MOVIMENTADA NUMERIC(6,2) NOT NULL,
  PRECO_PRODUTO NUMERIC(6,2) NOT NULL,
  TOTAL_ITEM NUMERIC(6,2) NOT NULL,
  PERCENTUAL_DESCONTO NUMERIC(5,2) DEFAULT 0,
  VALOR_DESCONTO NUMERIC(6,2),
  PERCENTUAL_ACRESCIMO NUMERIC(5,2),
  VALOR_ACRESCIMO NUMERIC(6,2),
  VALOR_FRETE NUMERIC(6,2) DEFAULT 0,
  TOTAL_GERAL_ITEM NUMERIC(7,2) NOT NULL,

   CONSTRAINT FK_MOVIMENTACAO_ITEM FOREIGN KEY (ID_MOVIMENTACAO) REFERENCES MOVIMENTACAO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

   CONSTRAINT FK_PRODUTO_MOVIMENTO FOREIGN KEY (ID_INSUMO_PRODUTO) REFERENCES PEDIDO_ITEM (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE FINANCEIRO(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_MOVIMENTACAO INT, 
  ID_SACADO INT NOT NULL,
  RECEBER_PAGAR VARCHAR(3) NOT NULL,
  TITULO SMALLINT,
  TITULO_VALOR_ORIGINAL NUMERIC(8,2) NOT NULL,
  VALOR_MULTA NUMERIC(7,2),
  SITUACAO VARCHAR(4) DEFAULT 'AB' NOT NULL,
  VALOR_TOTAL_PAGO NUMERIC(8,2),
  DATA_VENCIMENTO DATE, 
  DATA_QUITACAO DATE,
  ID_RESP_ALTERACAO INT,

  CONSTRAINT FK_FINANCEIRO_MOVIMENTO FOREIGN KEY (ID_MOVIMENTACAO) REFERENCES MOVIMENTACAO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT FK_SACADO_MOVIMENTO FOREIGN KEY (ID_SACADO) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT FK_RESP_ALTERACAO FOREIGN KEY (ID_RESP_ALTERACAO) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE FINANCEIRO_HISTORICO(
  ID INT IDENTITY  NOT NULL PRIMARY KEY,
  ID_TITULO INT NOT NULL,
  HISTORICO VARCHAR(200) NOT NULL, 
  DATA_MOVIMENTO DATE DEFAULT 'NOW'  NOT NULL,
  HORA_MOVIMENTO TIME DEFAULT 'NOW' NOT NULL,
  PERCENTUAL_DESCONTO NUMERIC(5,2),
  VALOR_DESCONTO NUMERIC(7,2),
  ID_RESP_DESCONTO_MANUAL INT,
  PERCENTUAL_JURO NUMERIC(5,2),
  VALOR_JURO NUMERIC(7,2),
  ID_RESP_JURO_MANUAL INT,
  TITULO_VALOR_TOTAL NUMERIC(8,2) NOT NULL,
  VALOR_PAGO NUMERIC(8,2) DEFAULT 0 NOT NULL,

  CONSTRAINT FK_TITULO_HISTORICO FOREIGN KEY (ID_TITULO) REFERENCES FINANCEIRO (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT FK_RESP_DESCONTO_MANUAL FOREIGN KEY (ID_RESP_DESCONTO_MANUAL) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,

  CONSTRAINT FK_RESP_JURO_MANUAL FOREIGN KEY (ID_RESP_JURO_MANUAL) REFERENCES PESSOA (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);